### ISSUE TITLE
Reorganize main README.md

### ISSUE THREAD

**Issue by pattacini** [robotology/yarp.js#12]
Hi @cciliber 

Concerning the beautiful tutorials you provide, what about reorganizing the quite long `README.md` - serving as entry point to the repo - in a suitable handful of other sub-readme (located in a `tutorials`-like sub-directory), which are then pointed from the main one?

**Comment by cciliber** [comment]
yup you are right... you told me one month ago but I got lazy I guess 

Will try to do it asap

**Comment by cciliber** [comment]
Ok, I have started re-arranging the structure of the README files. I have added a small description for the examples to each corresponding folder. Plus a small tutorial for some a couple of them. 

I am afraid the process is not over yet, but at least it started : )

Thanks for the suggestion!

**Comment by pattacini** [comment]
It's already quite neater now! 👍

**Comment by pattacini** [comment]
It might be that the latest changes you made broke the links...
