### ISSUE TITLE
executing examples.js out of yarp.js folder

### ISSUE THREAD

**Issue by bhigy** [robotology/yarp.js#14]
When running the example script out of yarp.js folder, the menu on the left is not working (where you can choose between speech recognition, audio streaming, ...). I suspect some relative path is used somewhere.

**Comment by cciliber** [comment]
Ok, I think it's solved now. It was indeed a local path thing. 

Thanks for pointing this out!

**Comment by bhigy** [comment]
Seems indeed to work. Thanks!
