### ISSUE TITLE
yarp.js does not build with Node.js version ≥ 12.22.1

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/yarp.js#19]
`yarp.js` does not build with Node.js versions:
- v12.22.1
- v14.17.0
- v16.3.0

But builds with Node.js version v4.9.1.

## Steps for reproducing the issue

- Node.js installed through NVM
    - node version: v14.17.0 (Latest LTS: Fermium)
    - npm version: v6.14.13
- YARP installed through the superbuild sources.
    - version: 3.4.3
    - Superbuild dependencies installed through conda.
    - Superbuild commit [abe2cb9](https://github.com/robotology/robotology-superbuild/commit/abe2cb99bea2a658298de0a18415944574f238da), built with ProjectTags "LatestRelease".
- yarp.js branch `master`, commit 56df066e255353e105af129ae98887309498c4c3.

Yarp.js build failed with error:
```
$ cd ~/dev/yarp.js
$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> YarpJS@1.0.0 install /Users/nunoguedelha/dev/yarp.js
> cmake-js

fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/nunoguedelha/dev/yarp.js/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/nunoguedelha/dev/yarp.js/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/nunoguedelha/dev/yarp.js/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/nunoguedelha/dev/yarp.js/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! YarpJS@1.0.0 install: `cmake-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the YarpJS@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nunoguedelha/.npm/_logs/2021-06-07T14_15_39_766Z-debug.log
```

Works with...
- node version: v4.9.1
- npm version: v2.15.11

So the maximum Node.js supporting yarp.js is somewhere in between. We need support for knowing what is the latest LTS version supporting the current `yarp.js`.

**Comment by traversaro** [comment]
Perhaps @Nicogene @vtikha @GiuliaDAngelo @randaz81 that used yarp.js in the last years may remember which version of node.js they used?

**Comment by GiuliaDAngelo** [comment]
Hi @traversaro, actually any version after 4.2.2 should be fine. 
Maybe, lately something changed significantly, I suggest you to try with the 4.2.2! 

Let me know :)

**Comment by traversaro** [comment]
Thanks @GiuliaDAngelo !

**Comment by nunoguedelha** [comment]
Thanks @GiuliaDAngelo . Actually, I had already tested  with node version v4.9.1 and it works. The thing is that version is really old (3 years). Latest version is 16.3.0.

yarp.js build fails with Node.js 16.3.0, 14.17.0, 12.22.1 . I added the build output in my initial description. A new symbol `primordials` was introduced, breaking compatibility with yarp.js.

Could you tell me which was the latest Node.js version you guys tested with yarp.js?

**Comment by nunoguedelha** [comment]
I've edited the issue title to be more clear.

CC @Nicogene @vtikha @GiuliaDAngelo @randaz81

**Comment by nunoguedelha** [comment]
Dug a bit more to see when the `primordials` object was used for the first time.

- Searched in all project for pattern "= primordials".
- Picked one of the files (`.../node/lib/internal/bootstrap/loaders.js`) matching and checked the file version history:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/6848872/121270277-afe20280-c8c1-11eb-8ff3-444590f0f83d.png">

The change was introduced in commit https://github.com/nodejs/node/commit/39d922123c02aecc2e289a08e3bdb9515a7b193a.

The latest Dubnium LTS release v10.24.1 does not use `primordials`.
The first Erbium LTS release v12.13.0 uses `primordials`.

So the latest Node.js version yarp.js ican build against is v10.24.1. Just checked that it builds ok.

**Comment by nunoguedelha** [comment]
## Some background on `primordials` object

https://stackoverflow.com/questions/59750976/what-are-primordials-in-node-js
https://github.com/nodejs/node/pull/30737
https://github.com/nodejs/node/blob/141a6e34eed05577edf43ad085a74f330d0559cb/lib/internal/per_context/primordials.js#L5-L7

> // This file subclasses and stores the JS builtins that come from the VM
> // so that Node.js's builtin modules do not need to later look these up from
> // the global proxy, which can be mutated by users.

> The primordials object is meant to be a way to guarantee that node builtin modules can access the true untampered globals instead of ones which may have been modified by users.

**Comment by GiuliaDAngelo** [comment]
Hi @nunoguedelha, I'm sorry I can't help you more than that with this problem.
The last time I used yarp.js was 3 years ago.
But it seems you found the latest version compatible :)

**Comment by nunoguedelha** [comment]
Ah indeed, it's far 😄 . Thanks anyway.

**Comment by nunoguedelha** [comment]
Actually the build with Node.js v10.24.1 is also failing. Refer to attached log. It was previously building because of left-over files in `node_modules`. After cleaning it, as well as the `build` folder, I tried again to build yarp.js and it fails.
[2021-06-09T14_38_25_486Z-debug.log](https://github.com/robotology/yarp.js/files/6624671/2021-06-09T14_38_25_486Z-debug.log)

So right now we are sure it works with Node.js 4.2.2.

**Comment by nunoguedelha** [comment]
## Socket.io required Node.js version

The `package.json` of `yarp.js` has the dependency `socket.io` set to "latest", so it installs version v4.1.2, which requires Node.js version ≥ 10.0.0. I couldn't find in the history of `package.json`, in the `socket.io` repo, the same dependency line with an older version of Node.js like v4.2.2, so I looked for it using the release dates, and found v1.5.1.

With this configuration, yarp.js build and installation are successful.

## Quick Recap for Successful Install so far

- Node.js installed through NVM
    - node version: v4.2.2 (Latest LTS: Argon)
    - npm version: v2.14.7
- YARP installed through the superbuild sources.
    - version: 3.4.3
    - Superbuild dependencies installed through conda.
    - Superbuild commit [abe2cb9](https://github.com/robotology/robotology-superbuild/commit/abe2cb99bea2a658298de0a18415944574f238da), built with ProjectTags "LatestRelease".
- yarp.js:  PR https://github.com/robotology/yarp.js/pull/18 (`fix/typo-in-include-cv-header` branch), commit https://github.com/robotology/yarp.js/commit/bba13848adbd4e8df8dce8e37f0c1a140a669649 on top of `master` branch.

**Comment by nunoguedelha** [comment]
Considering:
- the significant feature additions between node v4.2.2 and node v14.17.0 w.r.t. the Javascript language (https://node.green/), example:
  <img src="https://user-images.githubusercontent.com/6848872/139136858-df1e8847-1ba3-4ab5-aaa4-2bca2a0ae05d.png" height="250"/> <img src="https://user-images.githubusercontent.com/6848872/139136960-0b7ab7c2-12f6-4c91-ae3f-d57ac32df0fb.png" height="250"/>
- the improved debugging capabilities in Jetbrains's Webstorm IDE (debugger client compatible with node inspector from latest node LTS version v14.17.0),
- more particularly the support of package-lock.json (refer to https://github.com/ami-iit/yarp-openmct/issues/64),

upgrading the `Yarp.js` module to the latest Node.js LTS version should be considered kind of crucial. So I self-assigned this issue and moved it to the backlog. Any help (@Nicogene, @vtikha ) would be welcome.

**Comment by traversaro** [comment]
Great!

**Comment by Nicogene** [comment]
> upgrading the Yarp.js module to the latest Node.js LTS version should be considered kind of crucial. So I self-assigned this issue and moved it to the backlog. Any help (@Nicogene, @vtikha ) would be welcome.

Unfortunately, I have no expertise in Node.js, but yes seems a good idea!

**Comment by nunoguedelha** [comment]
I think it's better to just consider [here](https://github.com/robotology/yarp.js/issues/19#issuecomment-858705124) as the conclusion of this issue and open a new one for addressing https://github.com/robotology/yarp.js/issues/19#issuecomment-961941172.

**Comment by nunoguedelha** [comment]
Opened https://github.com/robotology/yarp.js/issues/28 for the upgrade. We can close this one.
