### ISSUE TITLE
Setup Lion environment for debugging Yarp and YarpJS.node libraries

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/yarp.js#31]
We need an advanced debug capability for analyzing issues like https://github.com/ami-iit/yarp-openmct/issues/51. For Javascript/Node.js code we have [**Webstorm**](https://www.jetbrains.com/webstorm), but we also need to debug the C++ addons and dependent libraries like **YarpJS.node** (Javascript-Yarp bindings), and for that we have [**CLion**](https://www.jetbrains.com/clion).

We document here the steps or particular settings (in MacOSX) for opening the CMake/make respective projects, select the proper compilation toolchain (cc, c++, clang, make) and CMake executable in order to build the project and be able to debug a running Javascript/Node,js process calling the libraries **YarpJS.node** and **Yarp** libraries, and doing so through breakpoints and stepping execution.

- [x] Build the superbuild and YARP project, **Release** configuration.
- [x] Load the YARP `Makefile` in CLion and check the index the code runs successfully. => :warning: but source code not loaded!
- [x] Build the YARP project **Debug** configuration. => OK
- [x] Load CMake project (`CMakeLists.txt`) as a project in CLion. => OK
- [x] Load the YARP `Makefile` in CLion as file first, then run the `Makefile`. => indexing and build OK.
- [x] Run a debug session and attach to a running process using YARP libraries (e.g. ~~Gazebo~~ node.js process).
- [x] Test stepping and breakpoints. > Not working so far.
- [x] Perform the same steps for **YarpJS**.

___

# Conclusion

For debugging the YARP component, it is easier to use Xcode. For debugging C++ code alongside Javascript code, i.e. `YarpJS.node` library built with `cmake-js` and `yarp.js` Javascript module, a CLion setup is required and quite efficient. For configuring the later, follow the steps listed below:

## Setup the CMake, Make, CLang Compilation Toolchain and Node.js Executable

https://www.jetbrains.com/help/clion/how-to-create-toolchain-in-clion.html
```
CLion > Preferences > Build,Execution,Deployment
```

- `> Toolchains`: created new Toolchain settings:
   <img width="891" alt="image" src="https://user-images.githubusercontent.com/6848872/146317783-a3cefa4b-5936-4157-81da-ebd0b9e12ab8.png">
   Make sure that the default required toolchain (`robotologydeps` described previously) is in the first position in order to be set as default.

- `> Makefile`: you can leave this section settings empty.
  <img width="1124" alt="image" src="https://user-images.githubusercontent.com/6848872/145954684-6014e462-6516-49ff-834f-fbd1f6e8ffa7.png">

- `> make`: Set the executable from the conda environment (This looks redundant, but set anyway):
   <img width="1129" alt="image" src="https://user-images.githubusercontent.com/6848872/145955164-bc943a31-6b53-4c87-8442-109206a4cc31.png">

- `> CMake`: Make sure that this toolchain settings result as follows:
  <img width="893" alt="image" src="https://user-images.githubusercontent.com/6848872/146317407-5454cc45-c5cd-40a8-afb4-93991106b34b.png">
  ...particularly the "Build directory" and "Environment" sections.
  The build option `--clean-first` in the CMake configuration is crucial for reconstructing all the symbols, and not just the ones from the changed files (there could be none).
  "Environment" field should be left empty as the environment has already been configured through the `EnvProj` plugin.
- Make sure you're selecting the proper Node.js interpreter
  <img width="1002" alt="image" src="https://user-images.githubusercontent.com/6848872/162733008-2b041e0f-e653-4308-ab6f-84606ffab0da.png">

## Set the Environment Variables

You need to set the environment variables from the **conda** environment used to compile YARP, since YARP is a dependency of the `YarpJS.node` library. For illustration purposes, let's consider you built YARP via the superbuild, under a Conda environment that we shall call `robotologydeps`<sup>*</sup>. Setting the environment variables from an `.env` file is not a native CLion feature. The plugin `ProjectEnv`, based on the former [**EnvFile**](https://plugins.jetbrains.com/plugin/7861-envfile), allows to do that.

- **Install the plugin:** Search for `ProjectEnv` in
  ```
  CLion > Preferences > Plugins
  ```
  <img width="1210" alt="image" src="https://user-images.githubusercontent.com/6848872/145995989-8224af24-478c-4f25-be2d-5f7b7b57a076.png">
- In a terminal, set the conda environment `robotologydeps` and print the environment variables to a **.env** file, e.g. `robotologydeps.env`.
  ```
  conda activate robotologydeps
  env > robotologydeps.env
  ```

- Enable the plugin and add `robotologydeps.env` to the plugin config
  ```
  CLion > Preferences > Build,Execution,Deployment > ProjectEnv Settings > Enable plugin > Select the .env files for the project
  ```
  <img width="1209" alt="image" src="https://user-images.githubusercontent.com/6848872/145998049-cbfa4ff1-05b8-4187-8559-8dffcc693484.png">

References:
https://plugins.jetbrains.com/plugin/7861-envfile
https://github.com/ashald/EnvFile
https://plugins.jetbrains.com/plugin/17044-projectenv
https://github.com/BredoGen/ProjectEnv

(*) For installing YARP...
- via the superbuild source code with dependencies provided by Conda => refer to https://github.com/robotology/robotology-superbuild#linux-macos-or-windows-from-source-with-dependencies-provided-by-conda-forge,
- as a standalone component from Conda packages -> run `conda install yarp`,
- as a standalone component with dependencies provided by Conda => refer to ...

## Loading YarpJS project

Unlike a classical, the `cmake-js` workflow has to be handled.

**Note:** We usually build the `yarp.js` repo from the terminal by running `npm install` which installs all the required dependencies and runs `cmake-js compile`. [**`cmake-js`**](https://github.com/unbornchikken/cmake-js) is a Node.js/io.js native addon build tool based on **CMake**. It invokes the CMake "configure" and "build" steps with specific parameters, using the **Ninja** Makefile generator by default.

There is a priori no easy way for integrating the `cmake-js` workflow in the CMake configuration of CLion, or running the actual respective `cmake-js.js` Javascript/Node.js executable from the IDE. There are an alternative for producing the same build result: run the CMake  **configure** step from the terminal, then run the **build** step from CLion IDE.

From the terminal where you activated the Conda environment `robotologydeps`, execute the following steps.

1. Install the repo as usual.
   ```
   npm install
   ```
2. Run the "configure" step.
   ```
   ./node_modules/cmake-js/bin/cmake-js -D configure
   ```

From the CLion application...

3. Open the `yarp.js` CMake project, selecting the top `CMakeLists.txt` and opening it as a project.

4. `Build > Build YarpJS`.

### References
https://www.jetbrains.com/help/clion/creating-new-project-from-scratch.html

### Note
For resetting and reloading the CMake project, do
```
Tools > CMake > Reset Cache and Reload Project
```

### Issues building the target

If no `YarpJS` target is available in step 4 for building...

- Edit the Run/Debug configurations
  <img width="644" alt="image" src="https://user-images.githubusercontent.com/6848872/162733622-27072280-980e-410a-8d7a-29346d43e70b.png">

- Add and setup a Run/Debug configuration of type **"CMake Application"** with the following settings:
   - target library code `YarpJS.node` C++ addon implementing the Javascript-C++ bindings
   - executable (has to be the node.js process running the javascript server application): `~/.nvm/versions/node/v14.17.0/bin/node`
   - Remove the default "before launch" operation `build` for not building at each run.
   - We depict below an example for running the `yarp-openmct` server
     <img width="1041" alt="image" src="https://user-images.githubusercontent.com/6848872/148047241-710d0516-c5d1-43b0-a123-d1be224d0e73.png">

### Selecting the  Node.js executable

Trying to select the executable `~/.nvm/versions/node/v14.17.0/bin/node` might not be possible if the file selector doesn't display the `.*` files. In such case, just copy/paste the absolute path.

### Working Directory

you have to set the absolute path. Using macros won't work for an unknown reason.

**Comment by nunoguedelha** [comment]
## Makefile Project

### Build the YARP (Release)
For starting, we run a YARP Release build. We do it through the superbuild, as documented in https://github.com/robotology/robotology-superbuild/blob/master/doc/conda-forge.md#source-installation.

### Open the YARP Makefile project
Open the project selecting the top position `Makefile` file in `<robotology-superbuild-path>/build/src/YARP`.

### Configure toolchain
https://www.jetbrains.com/help/clion/how-to-create-toolchain-in-clion.html

```
CLion ---> Preferences ---> Build,Execution,Deployment ---> Toolchains
```
- Created new Toolchain settings:
   <img width="1124" alt="image" src="https://user-images.githubusercontent.com/6848872/145954397-a9eeb389-e3b1-4b18-9ced-b2bdf13b5c81.png">

- Select Toolchain in `Makefile` settings:
   <img width="1124" alt="image" src="https://user-images.githubusercontent.com/6848872/145954684-6014e462-6516-49ff-834f-fbd1f6e8ffa7.png">

- Set `make` executable path (This looks redundant, but set anyway):
   <img width="1129" alt="image" src="https://user-images.githubusercontent.com/6848872/145955164-bc943a31-6b53-4c87-8442-109206a4cc31.png">

### Clean and Reload Makefile Project
In the lower left corner pane, click on "Clean and Reload Makefile Project":
<img width="256" alt="image" src="https://user-images.githubusercontent.com/6848872/145956609-55bd5060-f309-4295-bde7-c1703439097a.png">

- Output [Build FAILED]:
   <img width="1714" alt="image" src="https://user-images.githubusercontent.com/6848872/145955332-18937887-11a1-41cf-a952-550a0d29a966.png">

Before we analyse the issue, we give a try loading the **CMakefile** project.

**Comment by nunoguedelha** [comment]
...

The Environment variables were not set correctly in the CLion configuration.

After running again `cmake` and rebuilding the YARP target in the superbuild, we do the following...

### Set the Environment Variables
You need to set the environment variables from the **conda** environment used to compile YARP (let's call it `robotologydeps`, which includes all YARP dependencies and was activate when compiling YARP). Setting the environment variables from an `.env` file is not a native CLion feature. The plugin , based on the former [**EnvFile**](https://plugins.jetbrains.com/plugin/7861-envfile), .

- **Install the plugin:** Search for `ProjectEnv` in
  ```
  CLion > Preferences > Plugins
  ```
  <img width="1210" alt="image" src="https://user-images.githubusercontent.com/6848872/145995989-8224af24-478c-4f25-be2d-5f7b7b57a076.png">
- In a terminal, set the conda environment `robotologydeps` and print the environment variables to a **dotenv** file, e.g. `robotologydeps.env`.
  ```
  conda activate robotologydeps
  _switchRobot iCubGazeboV2_5
  _setupRobotologySuperbuild superbuild-soft-eng
  env > robotologydeps.env
  ```

- Enable the plugin and add `robotologydeps.env` to the plugin config
  ```
  CLion > Preferences > Build,Execution,Deployment > ProjectEnv Settings > Enable plugin > Select the .env files for the project
  ```
  <img width="1209" alt="image" src="https://user-images.githubusercontent.com/6848872/145998049-cbfa4ff1-05b8-4187-8559-8dffcc693484.png">

References:
https://plugins.jetbrains.com/plugin/7861-envfile
https://github.com/ashald/EnvFile
https://plugins.jetbrains.com/plugin/17044-projectenv
https://github.com/BredoGen/ProjectEnv

### Load the YARP Project `Makefile` again

==> Load successful without errors.

**Comment by nunoguedelha** [comment]
Opening the **Makefile** project does not load all the source files, so next step is to try with loading a **CMake** project.

**Comment by nunoguedelha** [comment]
## CMake Project

As in https://github.com/robotology/yarp.js/issues/31#issuecomment-993254366, we assume here that:
- YARP Release files have been built.
- The build toolchain in CLion is configured (Make, cc, c++)
- The environment settings file has been added to the `EnvProj` configuration.

### Open the CMake Project
https://www.jetbrains.com/help/clion/creating-new-project-from-scratch.html

Open the project selecting the top `CMakeLists.txt` in `<robotology-superbuild-root>/src/YARP`.

### Configure CMake
Go to the configuration pane...
```
CLion > Preferences > Build,Execution,Deployment
```
- Make sure that the `CMake` toolchain settings result as follows:
  <img width="998" alt="image" src="https://user-images.githubusercontent.com/6848872/146016523-22fbcecd-be86-49ef-b10f-225ef464990b.png">
  ...particularly the "Build directory" and "Environment" sections.
- "Environment" field should be left empty as the environment has already been configured through the `EnvProj` plugin.

### Reload the CMake Project
```
Tools > CMake > Reset Cache and Reload Project
```

The CMake configuration step fails with the output:
```
CMake Error at CMakeLists.txt:34 (find_package):
  By not providing "FindYCM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YCM", but
  CMake did not find one.

  Could not find a package configuration file provided by "YCM" (requested
  version 0.11.0) with any of the following names:

    YCMConfig.cmake
    ycm-config.cmake

  Add the installation prefix of "YCM" to CMAKE_PREFIX_PATH or set "YCM_DIR"
  to a directory containing one of the above files.  If "YCM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/nunoguedelha/dev/superbuild-soft-eng/robotology-superbuild/build/src/YARP/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:2533: cmake_check_build_system] Error 1
```

While processing the `CMakeLists.txt` directly, the CLion setup is not aware of the superbuild YCM configuration related to the first `cmake`configuration step run at the root of the superbuild. For taking that  into acount, probably the best would be to first run the superbuild `cmake` step in a terminal, then load the project opening the `CMakeCache.txt` which resulted from the first `cmake` configuration step.

**Comment by nunoguedelha** [comment]
CC @traversaro

**Comment by traversaro** [comment]
Note that if I remember correctly @drdanz @ste93 @elandini are also clion user, so perhaps they can share some tips and tricks on how to use Clion with CMake projects.

**Comment by nunoguedelha** [comment]
> The CMake configuration step fails with the output:
> 
> ```
> CMake Error at CMakeLists.txt:34 (find_package):
>   By not providing "FindYCM.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "YCM", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "YCM" (requested
>   version 0.11.0) with any of the following names:
> 
>     YCMConfig.cmake
>     ycm-config.cmake
> 
>   Add the installation prefix of "YCM" to CMAKE_PREFIX_PATH or set "YCM_DIR"
>   to a directory containing one of the above files.  If "YCM" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/nunoguedelha/dev/superbuild-soft-eng/robotology-superbuild/build/src/YARP/CMakeFiles/CMakeOutput.log".
> make: *** [Makefile:2533: cmake_check_build_system] Error 1
> ```

The following steps solve the problem:
- Load CMake project (CMakeLists.txt) as a project in CLion.
- Load the YARP Makefile in CLion as file first, then run the Makefile.

The YCM related problem disappears and the symbols are built correctly.

**Comment by nunoguedelha** [comment]
## Loading YarpJS project

We use the same compilation toolchain and CMake base settings as for the YARP project, but in addition, the `cmake-js` workflow has to be handled.

We usually build the `yarp.js` repo from the terminal by running `npm install` which installs all the required dependencies and runs `cmake-js compile`. [**`cmake-js`**](https://github.com/unbornchikken/cmake-js) is a Node.js/io.js native addon build tool based on **CMake**. It invokes the CMake "configure" and "build" steps with specific parameters, using the **Ninja** Makefile generator by default.

There is no way that I know of to easily integrate `cmake-js` workflow in the CMake configuration of CLion, or run the actual respective `cmake-js.js` Javascript/Node.js executable from the IDE. There are two alternative methods that should produce the same build result:
1. Run the CMake  **configure** step from the terminal, then run the **build** step from CLion IDE.
2. Create a **compilation database** and [load the **`yarp.js`** project from that database](https://www.jetbrains.com/help/clion/compilation-database.html#compdb_clion).

The method using the **compilation database** is promising, even for the YARP project, as it is independent from the build system used to compile the project in the terminal. The only requirement is that the build system should have the capability to export the compilation database.

**Comment by nunoguedelha** [comment]
##  Configure Step from the Terminal, Run step from CLion IDE

Running `cmake-js` from the terminal produces the result:
```
$ ./node_modules/cmake-js/bin/cmake-js -D compile
info TOOL Using Ninja generator, because ninja is available.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js" --no-warn-unused-cli -G"Ninja" -DCMAKE_JS_VERSION="3.2.1" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/build/Debug" -DCMAKE_JS_INC="/Users/nunoguedelha/.cmake-js/node-x64/v4.2.2/include/node;/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/node_modules/nan" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="4.2.2" -DNODE_ARCH="x64" -DCMAKE_CXX_FLAGS="-std=c++11 -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -w" -DCMAKE_SHARED_LINKER_FLAGS="-undefined dynamic_lookup"
Not searching for unused variables given on the command line.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is Clang 11.1.0
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/nunoguedelha/miniforge3/envs/robotologydeps/bin/x86_64-apple-darwin13.4.0-clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/nunoguedelha/miniforge3/envs/robotologydeps/bin/x86_64-apple-darwin13.4.0-clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found YARP: /Users/nunoguedelha/dev/superbuild-soft-eng/robotology-superbuild/build/install/lib/cmake/YARP (found version "3.4.6")
-- Found OpenCV: /Users/nunoguedelha/miniforge3/envs/robotologydeps (found version "4.5.3") 
CMake Deprecation Warning at /Users/nunoguedelha/dev/superbuild-soft-eng/robotology-superbuild/build/install/lib/cmake/YARP/YARPConfig.cmake:226 (message):
  The YARP_INCLUDE_DIRS variable is deprecated
Call Stack (most recent call first):
  CMakeLists.txt:9223372036854775807 (_yarp_deprecated_variable_warning)
  CMakeLists.txt:16 (include_directories)


-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   YarpJS

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/build
info CMD BUILD
info RUN cmake --build "/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/build" --config Debug
[12/12] Linking CXX shared library Debug/YarpJS.node
```

We can see that `cmake-js` first runs the "configure" step (`info CMD CONFIGURE...`), then a classical command line for the build step (`info RUN cmake --build "/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/build" --config Debug`). We don't want to overload the CMake configuration in CLion with an endless list of parameters that cann actually slightly change in the future depending on new versions of `cmake-js`. So this step will still be run on terminal.
On the other side, `cmake --build "/Users/nunoguedelha/dev/testYarpOpenMct/yarp.js/build" --config Debug` can be easily set in the CLion CMake configuration.

**Comment by nunoguedelha** [comment]
## Debug Session

1. We run the node app in terminal:
   ```
   $ node
   ```
2. Within the Node app, open a  port and connect it:
   ```
   > var yarp = require('./yarp')
   undefined
   > var port = yarp.portHandler.open('/yarpjs/inertial:i')
   [INFO] |yarp.os.Port| Port /yarpjs/inertial:i active at tcp://192.168.0.158:10098/
   undefined
   > var port = yarp.portHandler.open('/yarpjs/inertial:i')
   undefined
   ```
3. In CLion, set a breakpoint in `NAN_METHOD(YarpJS_Network::Connect)` function.
4. Attach to the Node process: `Run > Attach to process...`. Type "node" in the popup search box.
   <img width="454" alt="image" src="https://user-images.githubusercontent.com/6848872/146321002-10197567-1923-4173-b57e-74f6816f6c30.png">

5. Connect the ports:
   ```
   > yarp.Network.connect('/icubSim/inertial','/yarpjs/inertial:i')
   ```

The debugger doesn't trigger. Indeed we can see the error popup text as we swipe by the breakpoint:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6848872/146320232-9c2f259b-a8f3-4f2d-9ee6-cbc21a1af8dd.png">

This is the same issue we had with the YARP project.

**Comment by nunoguedelha** [comment]
It's actually working, I had forgotten to replace "Release" by "Debug" in the line https://github.com/robotology/yarp.js/blob/3eb91480064ace76089299c817832762d5f72f28/yarp.js#L2

for selecting the debug YarpJS.node instead of the release one.

#### Result when we connect the ports:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/6848872/146322529-ab5c25f3-f25e-432a-837b-29ffb18faf24.png">

**Comment by nunoguedelha** [comment]
## load the yarp.js project from a database

We apply this method to the project YARP since we still have issues using breakpoints on that project:
1. Create the database:
   ```
   cmake --build . --config Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --target YARP
   ```
2. Navigate to File | Open on the main menu, choose the compile_commands.json file or a directory that contains it, and click Open as Project.

**Comment by nunoguedelha** [comment]
https://github.com/robotology/yarp.js/issues/31#issuecomment-995454727
> 1. Run the "configure" step.
>   ```
>   ./node_modules/cmake-js/bin/cmake-js -D configure
>   ```
> 
> 2. Open the `yarp.js` project, selecting the repository root folder (not the `CMakeLists.txt` nor other build file!).

Actually, the steps should be:
2. Open the `yarp.js` project, selecting the repository `CMakeLists.txt`. The configure step fails. but without this step, the CMake build operation won't be available in step 7.
3. Run the "configure" step.
   ```
   ./node_modules/cmake-js/bin/cmake-js -D configure
   ```
...

**Comment by nunoguedelha** [comment]
> ## Load the Project from a Compilation Database
> 
> We apply this method to the project YARP since we still have issues using breakpoints on that project:
> 
>     1. Create the database:
>        ```
>        cmake --build . --config Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --target YARP
>        ```
> 
>     2. Navigate to File | Open on the main menu, choose the compile_commands.json file or a directory that contains it, and click Open as Project.

After loading the project from a compilation database, the YARP code is not fully indexed, and breakpoints are still not working.
