### ISSUE TITLE
Leave to YARP the pixel code conversion to CV channel order (BGRx)

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/yarp.js#43]
> I'm still finishing an approach based on @s-dafarra's suggestion, but it's already worth reviewing the implementation so far already discussed in the call.

_Originally posted by @nunoguedelha in https://github.com/robotology/yarp.js/issues/40#issuecomment-1098655428_

> Thanks, seems ok. Not sure if you want to check if we can do just with YARP but anyhow we can always merge this and improve it later.

_Originally posted by @traversaro in https://github.com/robotology/yarp.js/pull/40#pullrequestreview-941848509_

> > Thanks, seems ok. Not sure if you want to check if we can do just with YARP but anyhow we can always merge this and improve it later.
> 
> Thanks @traversaro , I will submit a separate PR for the improvement, as you suggested, that way it shall be easier to discuss around it and eventually discard it.

_Originally posted by @nunoguedelha in https://github.com/robotology/yarp.js/issues/40#issuecomment-1099213734_

**Comment by nunoguedelha** [comment]
## What was done so far

> <details>
> <summary>...</summary>
> 
> ## Convert the images to OpenCV JPEG format
> 
> ```c++
> /** @brief Encodes an image into a memory buffer.
> 
> The function imencode compresses the image and stores it in the memory buffer that is resized to fit the
> result. See cv::imwrite for the list of supported formats and flags description.
> 
> @param ext File extension that defines the output format.
> @param img Image to be written.
> @param buf Output buffer resized to fit the compressed image.
> @param params Format-specific parameters. See cv::imwrite and cv::ImwriteFlags.
> */
> CV_EXPORTS_W bool imencode( const String& ext, InputArray img,
>                             CV_OUT std::vector<uchar>& buf,
>                             const std::vector<int>& params = std::vector<int>());
> ```
> ```c++
> /** @brief Saves an image to a specified file.
> 
> The function imwrite saves the image to the specified file. The image format is chosen based on the
> filename extension (see cv::imread for the list of extensions). In general, only 8-bit
> single-channel or 3-channel (with 'BGR' channel order) images
> can be saved using this function, with these exceptions:
> 
> - 16-bit unsigned (CV_16U) images can be saved in the case of PNG, JPEG 2000, and TIFF formats
> - 32-bit float (CV_32F) images can be saved in PFM, TIFF, OpenEXR, and Radiance HDR formats;
>   3-channel (CV_32FC3) TIFF images will be saved using the LogLuv high dynamic range encoding
>   (4 bytes per pixel)
> - PNG images with an alpha channel can be saved using this function. To do this, create
> 8-bit (or 16-bit) 4-channel image BGRA, where the alpha channel goes last. Fully transparent pixels
> should have alpha set to 0, fully opaque pixels should have alpha set to 255/65535 (see the code sample below).
> - Multiple images (vector of Mat) can be saved in TIFF format (see the code sample below).
> 
> If the image format is not supported, the image will be converted to 8-bit unsigned (CV_8U) and saved that way.
> 
> If the format, depth or channel order is different, use
> Mat::convertTo and cv::cvtColor to convert it before saving. Or, use the universal FileStorage I/O
> functions to save the image to XML or YAML format.
> 
> The sample below shows how to create a BGRA image, how to set custom compression parameters and save it to a PNG file.
> It also demonstrates how to save multiple images in a TIFF file:
> @include snippets/imgcodecs_imwrite.cpp
> @param filename Name of the file.
> @param img (Mat or vector of Mat) Image or Images to be saved.
> @param params Format-specific parameters encoded as pairs (paramId_1, paramValue_1, paramId_2, paramValue_2, ... .) see cv::ImwriteFlags
> */
> CV_EXPORTS_W bool imwrite( const String& filename, InputArray img,
>               const std::vector<int>& params = std::vector<int>());
> ```
> ```c++
> enum ImwriteFlags {
>        IMWRITE_JPEG_QUALITY        = 1,  //!< For JPEG, it can be a quality from 0 to 100 (the higher is the better). Default value is 95.
>        IMWRITE_JPEG_PROGRESSIVE    = 2,  //!< Enable JPEG features, 0 or 1, default is False.
>        IMWRITE_JPEG_OPTIMIZE       = 3,  //!< Enable JPEG features, 0 or 1, default is False.
>        IMWRITE_JPEG_RST_INTERVAL   = 4,  //!< JPEG restart interval, 0 - 65535, default is 0 - no restart.
>        IMWRITE_JPEG_LUMA_QUALITY   = 5,  //!< Separate luma quality level, 0 - 100, default is 0 - don't use.
>        IMWRITE_JPEG_CHROMA_QUALITY = 6,  //!< Separate chroma quality level, 0 - 100, default is 0 - don't use.
>        IMWRITE_PNG_COMPRESSION     = 16, //!< For PNG, it can be the compression level from 0 to 9. A higher value means a smaller size and longer compression time. If specified, strategy is changed to IMWRITE_PNG_STRATEGY_DEFAULT (Z_DEFAULT_STRATEGY). Default value is 1 (best speed setting).
>        IMWRITE_PNG_STRATEGY        = 17, //!< One of cv::ImwritePNGFlags, default is IMWRITE_PNG_STRATEGY_RLE.
>        IMWRITE_PNG_BILEVEL         = 18, //!< Binary level PNG, 0 or 1, default is 0.
>        IMWRITE_PXM_BINARY          = 32, //!< For PPM, PGM, or PBM, it can be a binary format flag, 0 or 1. Default value is 1.
>        IMWRITE_EXR_TYPE            = (3 << 4) + 0, /* 48 */ //!< override EXR storage type (FLOAT (FP32) is default)
>        IMWRITE_EXR_COMPRESSION     = (3 << 4) + 1, /* 49 */ //!< override EXR compression type (ZIP_COMPRESSION = 3 is default)
>        IMWRITE_WEBP_QUALITY        = 64, //!< For WEBP, it can be a quality from 1 to 100 (the higher is the better). By default (without any parameter) and for quality above 100 the lossless compression is used.
>        IMWRITE_PAM_TUPLETYPE       = 128,//!< For PAM, sets the TUPLETYPE field to the corresponding string value that is defined for the format
>        IMWRITE_TIFF_RESUNIT = 256,//!< For TIFF, use to specify which DPI resolution unit to set; see libtiff documentation for valid values
>        IMWRITE_TIFF_XDPI = 257,//!< For TIFF, use to specify the X direction DPI
>        IMWRITE_TIFF_YDPI = 258, //!< For TIFF, use to specify the Y direction DPI
>        IMWRITE_TIFF_COMPRESSION = 259, //!< For TIFF, use to specify the image compression scheme. See libtiff for integer constants corresponding to compression formats. Note, for images whose depth is CV_32F, only libtiff's SGILOG compression scheme is used. For other supported depths, the compression scheme can be specified by this flag; LZW compression is the default.
>        IMWRITE_JPEG2000_COMPRESSION_X1000 = 272 //!< For JPEG2000, use to specify the target compression rate (multiplied by 1000). The value can be from 0 to 1000. Default is 1000.
>      };
> ```
> 
> The current parameters `p` are
> https://github.com/robotology/yarp.js/blob/d2e4609c5115544c3837eb36fa38065aa06a343f/YarpJS/src/YarpJS_Image.cpp#L34-L35
> 
> No additional parameter here is meant to convert the channel order.
> 
> > If the format, depth or channel order is different, use
> > Mat::convertTo and cv::cvtColor to convert it before saving. ...
> > 
> 
> ### cvtColor(...)
> 
> > /** @brief Converts an image from one color space to another.
> > 
> > The function converts an input image from one color space to another. In case of a transformation
> > to-from RGB color space, the order of the channels should be specified explicitly (RGB or BGR). Note
> > that the default color format in OpenCV is often referred to as RGB but it is actually BGR (the
> > bytes are reversed). So the first byte in a standard (24-bit) color image will be an 8-bit Blue
> > component, the second byte will be Green, and the third byte will be Red. The fourth, fifth, and
> > sixth bytes would then be the second pixel (Blue, then Green, then Red), and so on.
> > 
> > The conventional ranges for R, G, and B channel values are:
> > -   0 to 255 for CV_8U images
> > -   0 to 65535 for CV_16U images
> > -   0 to 1 for CV_32F images
> > 
> > In case of linear transformations, the range does not matter. But in case of a non-linear
> > transformation, an input RGB image should be normalized to the proper value range to get the correct
> > results, for example, for RGB $\rightarrow$ L\*u\*v\* transformation. For example, if you have a
> > 32-bit floating-point image directly converted from an 8-bit image without any scaling, then it will
> > have the 0..255 value range instead of 0..1 assumed by the function. So, before calling #cvtColor ,
> > you need first to scale the image down:
> > @code
> >     img *= 1./255;
> >     cvtColor(img, img, COLOR_BGR2Luv);
> > @endcode
> > If you use #cvtColor with 8-bit images, the conversion will have some information lost. For many
> > applications, this will not be noticeable but it is recommended to use 32-bit images in applications
> > that need the full range of colors or that convert an image before an operation and then convert
> > back.
> > 
> > If conversion adds the alpha channel, its value will set to the maximum of corresponding channel
> > range: 255 for CV_8U, 65535 for CV_16U, 1 for CV_32F.
> > 
> > @param src input image: 8-bit unsigned, 16-bit unsigned ( CV_16UC... ), or single-precision
> > floating-point.
> > @param dst output image of the same size and depth as src.
> > @param code color space conversion code (see #ColorConversionCodes).
> > @param dstCn number of channels in the destination image; if the parameter is 0, the number of the
> > channels is derived automatically from src and code.
> > 
> > @see @ref imgproc_color_conversions
> >  */
> > CV_EXPORTS_W void cvtColor( InputArray src, OutputArray dst, int code, int dstCn = 0 );
> > 
> 
> </details>

_Originally posted by @nunoguedelha in https://github.com/robotology/yarp.js/issues/41#issuecomment-1097026178_

___

We were generating a conversion code from the actual pixel code of the received image...
```
VOCAB_PIXEL_RGB ---> cv::COLOR_RGB2BGR
```
https://github.com/robotology/yarp.js/blob/f100ce6ecff8676707e61bc8bf56bf5fb4bf3181/YarpJS/src/YarpJS_Image.cpp#L55

..., then calling directly `cv::cvtColor` for converting the pixel code in place
https://github.com/robotology/yarp.js/blob/f100ce6ecff8676707e61bc8bf56bf5fb4bf3181/YarpJS/src/YarpJS_Image.cpp#L59

Actually a function within YARP already does this job. The conversion code is generated in https://github.com/robotology/yarp/blob/702271e6f0fb685847938a2d892c0f629aab29f6/src/libYARP_cv/src/yarp/cv/Cv-inl.h#L35-L48
```c++
template<> struct convert_code_to_cv<yarp::sig::PixelMono> : std::integral_constant<int, -1> {};
template<> struct convert_code_to_cv<yarp::sig::PixelMono16> : std::integral_constant<int, -1> {};
template<> struct convert_code_to_cv<yarp::sig::PixelMonoSigned> : std::integral_constant<int, -1> {};
...
```

which is used in the pixel conversion done in https://github.com/robotology/yarp/blob/702271e6f0fb685847938a2d892c0f629aab29f6/src/libYARP_cv/src/yarp/cv/Cv-inl.h#L72-L82
```c++
template<typename T>
::cv::Mat yarp::cv::toCvMat(yarp::sig::ImageOf<T>& yarpImage)
{
    ::cv::Mat outMat (yarpImage.height(), yarpImage.width(), yarp::cv::type_code<T>::value,
                      yarpImage.getRawImage(), yarpImage.getRowSize()); // RVO
    if (convert_code_to_cv<T>::value >= 0)
    {
        ::cv::cvtColor(outMat, outMat, convert_code_to_cv<T>::value);
    }
    return outMat;
}
```

___

**So we can reuse this method in a few steps:**
1. get the pixel code from the original image (e.g. `VOCAB_PIXEL_RGB`).
2. Retrieve the respective specialization of `yarp::cv::toCvMat` from a predefined `std::map` (e.g. `&yarp::cv::toCvMat<yarp::sig::PixelRgb>`)
3. Cal the obtained `yarp::cv::toCvMat` passing to it the casted original image `this->getYarpObj()`.

#### Implementaton issue
There is a problem with the definition of the map `yarpCode2toCvMat`: for adding another line with a different pixel code (e.g. `yarp::sig::PixelMono`), I would need to have a generic type `x` in the declaration of the map, which accepts both `yarp::sig::PixelMono` and `yarp::sig::PixelRgb` (like a "union"). Same applies to all the other lines in `yarpCode2toCvMat` still commented. Using a parent class of `ImageOf`, i.e. `Image` doesn't seem to work.

Analyzing...

**Comment by nunoguedelha** [comment]
Ideally, `yarpCode2toCvMat` should also be on the YARP side.
https://github.com/robotology/yarp.js/blob/52d21d12c1611548b0fcf46e151801d2d3ef5ecd/YarpJS/src/YarpJS_Image.cpp#L23

**Comment by S-Dafarra** [comment]
Hold on! I was simply suggest to do
```c++
yarp::os::ImageOf<yarp::sig::PixelBgr> imageBgr;
imageBgr = whateverOtherYarpImageWeHaveAsInput;
doSomething(imageBgr);
```
``yarp::cv`` is yet another thing, but at this point I am not sure how worth is to dig into that

**Comment by nunoguedelha** [comment]
I got it, but this isn't enough for converting the pixel code. In any case, the main motivation here is to delegate to Yarp as much as possible the logic determining which format conversions are supported and actually doing those conversions, for not duplicating critical information.

As we can see in https://github.com/robotology/yarp.js/pull/44, I'm doing a `static_cast` of the orginal `yarp::sig::Image` to a `yarp::sig::ImageOf`, but you need to convert the image to a `cv::Mat` format. This used to be done by `getIplImage()`, as in
https://github.com/robotology/yarp.js/blob/f100ce6ecff8676707e61bc8bf56bf5fb4bf3181/YarpJS/src/YarpJS_Image.cpp#L36

then `getIplImage()` got deprecated, the usage of `yarp::cv::toCvMat` being recommended instead
https://github.com/robotology/yarp/blob/702271e6f0fb685847938a2d892c0f629aab29f6/src/libYARP_sig/src/yarp/sig/Image.h#L295-L303
```c++
#ifndef YARP_NO_DEPRECATED // Since YARP 3.2.0
    /**
     * Returns IPL/OpenCV view of image, if possible.
     * Not possible if the image is the wrong size, with no padding.
     * This method is currently not well documented.
     * @return pointer to an IplImage structure or nullptr
     */
    YARP_DEPRECATED_MSG("Use yarp::cv::toCvMat instead")
    void *getIplImage();
```

**Comment by S-Dafarra** [comment]
Ah ok, I did not understand that you were also trying to get around the deprecation of ``getIplImage``. My comment was merely related to the conversion to the desired pixel code. In this regard, can you elaborate on 

> I got it, but this isn't enough for converting the pixel code.

?

**Comment by nunoguedelha** [comment]
I might be wrong, but as far as I understood, the operator "=" does not convert images from one pixel code to another.

**Comment by nunoguedelha** [comment]
Underneath, the `copy` operator must be called, and that one might do the conversion...

**Comment by S-Dafarra** [comment]
> I might be wrong, but as far as I understood, the operator "=" does not convert images from one pixel code to another. Let me check...

That's what I meant instead :wink:

> Underneath, the `copy` operator must be called, and that one might do the conversion...

Yes, it is a deep copy. ``ImageOf`` inherits from ``Image``, and it defines the assignment operator: https://github.com/robotology/yarp/blob/043326d4f763c3ce9da43bf7399a86c2bfb0c310/src/libYARP_sig/src/yarp/sig/Image.h#L108 that inside calls ``copy`` https://github.com/robotology/yarp/blob/043326d4f763c3ce9da43bf7399a86c2bfb0c310/src/libYARP_sig/src/yarp/sig/Image.cpp#L827-L833

**Comment by nunoguedelha** [comment]
Actually I had already tried the `copy` method directly, but I had used the wrong type `yarp::sig::PixelRgb` instead of `yarp::sig::PixelBgr` by mistake (the `yarp::cv::toCvMat` is the other way around, you specify the source pixel code, not the dest, the dest being always BGR).

Anyway, this is cool because, with the `copy`, we don't need to have to any map indexed by the pixel code and depending on the list of supported pixel codes. Thanks!

We can still use `yarp::cv::toCvMat` and ditch `getIplImage` and `cv::cvarrToMat`.

**Comment by nunoguedelha** [comment]
I had to use `copy` instead of the `=` operator, which wasn't compiling for some reason (I would expect it to work since the argument in `=` prototype is an `Image`.

The drawback of using `yarp::sig::Image::copy` instead of `yarp::cv::toCvMat` is that we loose the alpha channel if we use systematically the pixel type `PixelBgr`, so I replaced it by `PixelBgra`. This way, in case the original image has an alpha channel, we conserve it, otherwise we set it to 255 (maximum opacity).

**Comment by nunoguedelha** [comment]
> #### Implementaton issue
> 
> There is a problem with the definition of the map `yarpCode2toCvMat`: for adding another line with a different pixel code (e.g. `yarp::sig::PixelMono`), I would need to have a generic type `x` in the declaration of the map, which accepts both `yarp::sig::PixelMono` and `yarp::sig::PixelRgb` (like a "union"). Same applies to all the other lines in `yarpCode2toCvMat` still commented. Using a parent class of `ImageOf`, i.e. `Image` doesn't seem to work.

**Side note here, although the approach mentioned above was dropped...**

Instead of the `std::map` we could have simply used a `switch`. The map should be faster in runtime though, which was my main motivation in using it.
