### ISSUE TITLE
`toArray()` returns wrong content or crashes the running process

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/yarp.js#49]
The `_yarp.Bottle().toArray()` method either returns an empty array, or returns an array with wrong content, or crashes the running **Node.js** process.

Occurred on [`yarp-openmct#47a887c`](https://github.com/ami-iit/yarp-openmct/commit/47a887ce926e310bdd07fd9b3aa47fa5038a30a6), along with [`yarp.js#3eb9148`](https://github.com/robotology/yarp.js/commit/3eb91480064ace76089299c817832762d5f72f28).

Issue moved from https://github.com/ami-iit/yarp-openmct/issues/145:
> For the second call, with `id = 'sens.headIMU'` (M.A.S. sensor data),...
> - `bottle.toString()` returns `(((-0.240112648394806865726 0.256409150712710476316 1.25491568355236471355) 4336.35999999999967258)) (((-0.152372687054658478845 -0.0560934592355309263878 -9.73042375287977989728) 4336.35999999999967258)) (((0.0 0.0 0.0) 4336.35999999999967258)) (((0.000133744890740640628643 -0.00548904149557477138294 2.25436842049552410572) 4336.35999999999967258)) () () () () () ()`
> - `bottle.toArray()` returns `Array(10) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`.
> 
> `bottle.toArray()` should return the same content instead of zeros. So, for nested bottles, either we get a wrong result or we get a segmentation fault. **This is a YarpJS bug.**.
> 
> Moving the issue to YarpJS repo.
> 

_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/145#issuecomment-1322986579_

`_yarp.Bottle()` is wrapped as follows within the YarpJS module:

https://github.com/robotology/yarp.js/blob/08c9c2cd6b6957f45ffb58779bc998252d7c5269/yarp.js#L2

https://github.com/robotology/yarp.js/blob/08c9c2cd6b6957f45ffb58779bc998252d7c5269/yarp.js#L31-L34

The bottle object `_yarp_wrap_object(obj)` is passed to the `onRead()` callback upon reception of a Yarp message.
https://github.com/robotology/yarp.js/blob/08c9c2cd6b6957f45ffb58779bc998252d7c5269/yarp.js#L184-L190

Within that callback, calling the method `toArray()` of the bottle crashes the running **Node.js** process.

**Comment by nunoguedelha** [comment]
The issue is related to the generated library `YaprJS.node` in the folder `<repo-root>/build/Release`.

In the failing case, the library `YaprJS.node` dependency `libYARP_os.3.dylib` (Yarp OS module implementing the bottle) has the version:
```
@rpath/libYARP_os.3.dylib (compatibility version 3.0.0, current version 3.5.1) => yarp version 3.5.1
```

while the same dependency in the working case has the version:
```
@rpath/libYARP_os.3.dylib (compatibility version 3.0.0, current version 3.7.2) => yarp version 3.7.2
```
In both cases the activated Conda environment had yarp version 3.7.2 installed.

**Note:** This information can be obtained with the `otool` command:
```
otool -L <yarp-openmct-path>/node_modules/YarpJS/build/Release/YarpJS.node
```

If we rebuild `YarpJS.node` from scratch in a Conda environment with **Yarp 3.5.1** (or **3.7.2**), and run the application on the same environment, the issue never occurs again. The issue only occurs if we build `YarpJS.node` in a Conda environment with **Yarp 3.5.1** and then swith to an environment with **Yarp 3.7.2**. So the issue is due to a misalignment between the versions of the `YarpJS.node` library and its dependencies.

### Further Observations
For some reason, the issue never occurs if we run `npm start`, which actually runs `cd iCubTelemVizServer && node iCubTelemVizServer.js`. introducing `yarp --version`, or `env > env-npm-start.txt` in this command allows to check respectively the yarp version or environment variables used in the child shell. The used yarp version was strictly the same and no difference relevant to this issue was observed in the environment variables, typically the RPATH
```
LDFLAGS_LD=-pie -headerpad_max_install_names -dead_strip_dylibs -rpath /Users/nunoguedelha/miniforge3/envs/robotologydeps3/lib -L/Users/nunoguedelha/miniforge3/envs/robotologydeps3/lib
```

[env-node-iCubTelemVizServer.txt](https://github.com/robotology/yarp.js/files/10070987/env-node-iCubTelemVizServer.txt)

[env-npm-start.txt](https://github.com/robotology/yarp.js/files/10070988/env-npm-start.txt)


#### Nevertheless, we can assume the misalignment between the library `YarpJS.node` version and its dependencies versions. The safest workflow to follow in order to avoid the issue is to rebuild `YarpJS.node` every time we change yarp version.

**Comment by nunoguedelha** [comment]
I think it's not worth spending more time on this issue, and we should close it.

CC @S-Dafarra @traversaro

**Comment by traversaro** [comment]
> Nevertheless, we can assume the misalignment between the library `YarpJS.node` version and its dependencies versions. The safest workflow to follow in order to avoid the issue is to rebuild `YarpJS.node` every time we change yarp version or OpenCV btw.

Yes, this is the expected as neither OpenCV nor YARP ensure any kind of ABI compatibility (see https://abi-laboratory.pro/?view=timeline&l=opencv), so it is kind of expected that you need to rebuild a C++ project once one of its dependencies changes version.  

> I think it's not worth spending more time on this issue, and we should close it.

Yes, the behaviour described in this issue is the expected one, so I agree.
